idf_component_register(
    SRCS
        "main.c"
        "aronet_device_client.c"
        "aronet_device_gui.c"
        "display_driver.c"
        "display_init.c"
        "touch_driver.c"
        "hw_version.c"
        "screen_orientation.c"
        "../managed_components/lvgl__lvgl/demos/multilang/assets/fonts/font_multilang_small.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        lvgl__lvgl
        esp_lcd
        esp_timer
        driver
        nvs_flash
        esp_psram
        esp_http_client
        esp_wifi
        esp_event
        esp_netif
        cjson
)
