idf_component_register(
    SRCS
        "main.c"
        "aronet_device_client.c"
        "aronet_device_gui.c"
        "display_driver.c"
        "display_init.c"
        "touch_driver.c"
        "hw_version.c"
        "screen_orientation.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        esp_lcd
        esp_timer
        driver
        nvs_flash
        esp_psram
        esp_http_client
        esp_wifi
        esp_event
        esp_netif
        cjson
)
